disabled = false
languageCode = "fr"
languageName = "Fran√ßais"
weight = 1
title = "Publics Progressistes"

[params]
  displayName = "FR"
  isoCode = "fr"
  rtl = false
  dateFormat = "2 Janvier 2006"
  description = "Publics Progressistes"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"

