disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Progressive Publics"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  description = "Progressive Publics"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"

